apiVersion: apps/v1
kind: Deployment
metadata:
  name: codewire-demo-site
  labels:
    app: codewire-demo-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codewire-demo-site
  template:
    metadata:
      labels:
        app: codewire-demo-site
    spec:
      imagePullSecrets:
        - name: gitea-registry
      containers:
        - name: demo-site
          image: REGISTRY_URL/IMAGE_NAME:IMAGE_TAG
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              cpu: "20m"
              memory: "32Mi"
            limits:
              cpu: "100m"
              memory: "64Mi"
